### ISSUE TITLE
Heatmap cell padding broken?

### ISSUE THREAD

**Issue by oscarlofwenhamn** [reaviz/reaviz#6]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release) **i guess**
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When rendering a Heatmap and CalendarHeatmap, the cells are rendered with too much padding, making the component unusable. 

Heatmap example from [Reaviz demo code](https://codesandbox.io/s/reaviz-codesandbox-template-jpw6m?from-embed):
![image](https://user-images.githubusercontent.com/44643697/87937841-c60e8680-ca95-11ea-9553-d2bf3dfe2321.png)

CalendarHeatmap from my own project:
![image](https://user-images.githubusercontent.com/44643697/87937915-f2c29e00-ca95-11ea-8367-fc36aaab1b62.png)

## Expected behavior

Correctly rendered Headmap and CalendarHeatmap

## Minimal reproduction of the problem with instructions
Visit https://codesandbox.io/s/reaviz-codesandbox-template-jpw6m?from-embed

**Comment by amcdnl** [comment]
resolved.

**Comment by oscarlofwenhamn** [comment]
This is still broken in my local implementation, though now it indeed works in the demo. I've also tried the demo using the dependencies from my project, and it still works; what influences the padding settings for the heatmap cells, and is there any way of directly influencing them?
